### ISSUE TITLE
Project Box layout

### ISSUE THREAD

**Issue by apercas** [Vizzuality/openDRI#113]
Hello, @shanikadhettige and @vdeparday we've created a template as you requested, here is the example http://opendri.simbiotica.es/project/project-box-example/

As mentioned in the PR https://github.com/Vizzuality/openDRI/pull/112 and as you can see in the project edit view, the template code is https://gist.github.com/apercas/67f23608376fbe7391a83e7ddb756172 

Hope you like it:
![image](https://cloud.githubusercontent.com/assets/704210/14637723/793aa1a2-0633-11e6-9e63-914e893937a5.png)

Thanks!

**Comment by shanikadhettige** [comment]
I like how this looks but I think the intention of @vdeparday and @rsoden was to have this on the side of a project page, the equivalent of where the related resources would go on a news page. They should confirm about what they think and let you know how to move forward.

**Comment by vdeparday** [comment]
No, @apercas is right, this is where we wanted the box. On the right side, we talked about Related News.

That is looking good and giving more flesh to the project page. I think we need two more css style, one for a list item that is horizontal (text for instance) instead of vertical like the current one (we will need the vertical one too, so keep it there ;) )  and for a paragraph heading. For instance to list a URL or a partner.

For instance: 
GeoNode URL: www.riskinfo.lk
Counterpart: Disaster Management Center, Ministry of Disaster Management

And there could be other items like that for a given country.

And then (unrelated to the box) if we could have a nice style for the heading we have currently in the pages like Collecting, etc... that would be great. We could use the lower size font version of it for the box if we need it.

**Comment by shanikadhettige** [comment]
Oh yes, I remember and understand the placing now. My mistake.

Over the next few days I will need to go back through all the project content to add some background info. I can add this information from the spreadsheet at the same time, do I just copy the code and paste it in the top of the HTML text part of the project editing box? @vdeparday and @apercas Please let me know when it is completely ready to use.

**Comment by apercas** [comment]
Updated: http://localhost:8888/odri/project/project-box/

**Comment by vdeparday** [comment]
I am not sure on the link to localhost ;) but the screenshot in issue #99 looks good to me.

**Comment by apercas** [comment]
Ha! My fault! This is the URL I meant to paste http://opendri.simbiotica.es/project/project-box-example/ But glad it is OK! Closing :)
