### ISSUE TITLE
Wrong font an IE

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#139]
Doing a couple check on IE since it is the one that opens the link by default here. It looks like the font is not getting detecting, the thumbnails have a time new roman type font that makes things not look good. 

![image](https://cloud.githubusercontent.com/assets/1036189/15257467/7d246c28-1914-11e6-8d4e-2c0cf6c47688.png)

**Comment by apercas** [comment]
Hum, it seemed the font we're using (Bariol) had an issue with IE (but not Edge) on the version we were using, we changed it and now it's been displayed better, could you please check? Thank you!

**Comment by vdeparday** [comment]
What do you mean by "but not Edge", does that mean that we are no longer
using Bariol?

It looks much better now although still slighty different but that is fine.

**Comment by apercas** [comment]
Hi, we're still using Bariol and we will keep it. When i said that i meant that the bug existed on IE but not on IE's predecessor, Edge. The font is slightly different because the type format for those browser is not the same as the one Firefox or Chrome use, even different versions of the same browsers can render the typographies differently. That's why we face this differences :)

**Comment by vdeparday** [comment]
Thanks for the clarification !

**Comment by vdeparday** [comment]
Thanks for the clarification !
