### ISSUE TITLE
First lines of text editor are not visible

### ISSUE THREAD

**Issue by cgiovando** [Vizzuality/openDRI#187]
See the attached screenshot. The tag toolbar covers the first an half line of the text editor form.

<img width="746" alt="screen shot 2016-08-09 at 11 38 28" src="https://cloud.githubusercontent.com/assets/10201533/17528912/1693155c-5e26-11e6-9a1d-24201d3a383e.png">

**Comment by shanikadhettige** [comment]
Hi Cristiano,

If you change the size of your window to be larger this should be fixed.

On Tue, Aug 9, 2016 at 2:40 PM, Cristiano Giovando <notifications@github.com

**Comment by cgiovando** [comment]
Do you mean the browser window? I have it expanded all the way at 2560x1600, but the bar is still covering it. The only way to show it - that I just found out - is to click on the "fullscreen" button. If that is the way it's meant to work, then feel free to close this ;)

I'm on Chrome version 52.0.2743.116, OSX 10.11.6

**Comment by shanikadhettige** [comment]
I'm not sure if that's the way it's supposed to work but have had to do the same thing on my laptop.

@apercas?

**Comment by apercas** [comment]
Hi, I think I didn't experienced this because of my screen resolution:
![image](https://cloud.githubusercontent.com/assets/704210/17691909/72b36dfc-6397-11e6-81a9-145721a45bf7.png)

But actually this is a documented failure: https://wordpress.org/support/topic/css-bug-when-working-on-a-small-screen-the-first-line-is-not-fully-visible

I've updated the plugin and tried on different screen sizes, this shouldn't be an issue anymore :)

PS: For incoming tickets you want me to check, please assign them directly to me, otherwise I could accidentally skip them. Thanks :)

**Comment by shanikadhettige** [comment]
@cgiovando Let us know if this remains a problem on your machine. I'll close this issue for the time being
