### ISSUE TITLE
Add Capability Manager Plugin

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#203]
For whatever reason my account won't let me add plugins
https://wordpress.org/plugins/capability-manager-enhanced/installation/

**Comment by apercas** [comment]
Hi, quick explanation. It's not because of your or my account. A Pantheon server (as an Heroku server) won't let you install anything as they won't allow you to write / edit a file as a regular server will do because the only thing they do is reading files (and they're really quick at it). That's why we'll never have the chance to add a plugin unless directly from the `/wp-admin`, but we'll be able to add one if we upload it and deploy the change :)

That being said, I'll ping you back when it's deployed.

**Comment by shanikadhettige** [comment]
Ok, let me know - thanks!

**Comment by apercas** [comment]
Added :)

**Comment by shanikadhettige** [comment]
Thanks!!
