### ISSUE TITLE
GeoNode Deployment Guide

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#78]
- [x] Change colors to be less blue, show logo better
- [x] Add as a Notes resource and add link to the Pillars on About Page

**Comment by shanikadhettige** [comment]
@vdeparday Please find the following files created/revised and uploaded as resources and let me know that all is OK. 
- [Community Mapping Factsheet](http://dev-gfdrr-opendri.pantheonsite.io/resource/873/) _Notes_
- [Sharing Data Factsheet](http://dev-gfdrr-opendri.pantheonsite.io/resource/sharing-data-factsheet/) _Notes_
- [GeoNode Deployment Guide](http://dev-gfdrr-opendri.pantheonsite.io/resource/geonode-deployment-guide/) (Digital Version) _Tools and Training Materials_

Do you still want to add them to the Pillars? I think we should wait on that as we don't have a good example for Using Data. If OK please close issue.

**Comment by vdeparday** [comment]
Great ! Thank you. Just some quick fixes: 
for the community mapping one, can we update the reference to the Open Cities guied to refer to the OpenDRI website (it will be easier for people to find).

For the deployment guide, can we use blue instead of red? The same as in the website boxes and heading? It will be more consistent. 

No need to add under the pillars for now but we can add them in the Short Note section of the resource page.

You can close the issue once you made the quick fixes and they are made available under the resources 

Thanks a lot.

**Comment by shanikadhettige** [comment]
Made the changes and reuploaded. 
- Community Mapping Factsheet now references Guide found at www.opendri.org under Resources
- Tried the red for deployment guide since before you weren't sure if everything was too blue but I prefer the blue also. 

Closing now.
