### ISSUE TITLE
Please add the OpenDRI logos with background to Brand Guidelines site

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#82]
https://basecamp.com/1756858/projects/10211583/uploads/30621119#comment_399087384

**Comment by agnlez** [comment]
Sorry @shanikadhettige, I didn't understand you. What do you mean by adding the logos with background? We already have the OpenDRI logos added in the site (http://vizzuality.github.io/innovation-lab-brand-guidelines/brand-guidelines/download-resources.html). Maybe we caught it wrong, is there anything wrong?

Thanks!

**Comment by shanikadhettige** [comment]
Hi @andresgnlez,
I mean the one found at this link https://basecamp.com/1756858/projects/10211583/uploads/30621119#comment_399087384 regarding the comments on Basecamp about those who do not have AI and cannot change the transparency before using in an email, for example

**Comment by shanikadhettige** [comment]
https://asset1.basecamp.com/1756858/projects/10211583/attachments/218208959/OpenDRI-logo.ai

**Comment by agnlez** [comment]
We have just updated the site again, we have fixed the current logos and added new ones with background as you can see here: http://vizzuality.github.io/innovation-lab-brand-guidelines/brand-guidelines/download-resources.html

Thanks!

**Comment by shanikadhettige** [comment]
@andresgnlez Could we do this for all the logos for different teams, not just the first two OpenDRI ones? Otherwise those that are uploaded are OK and can be closed once they are added.

**Comment by danicaso-vizzuality** [comment]
Hi @shanikadhettige ,
Sorting out this issue, taking it up from the beginning, The png version of each logo are meant to be used anywhere (e-mail, word, etc.) without using Illustrator or any other program. So that issue would be sorted out without including these last versions. 
I would recommend get rid of these last versions in order keep it as simpler as possible avoiding confusion when a user wanted to download a logo and find so many options (more than needed).
Looking forward to hearing your thoughts about this.
Thank you

**Comment by shanikadhettige** [comment]
Yes I understand that the PNGs are good for e-mail, word, etc but the problem was that the ones that are white were coming with a transparent background so on a white page they can't be seen, right? If we just swap out the files that is also fine.

**Comment by danicaso-vizzuality** [comment]
That is the aim of having multiple color options to download. For most of the cases, the standard version will be the right one. The other ones are meant to be used over darker backgrounds.

That said, and if you agree with it, we will proceed to get rid of those versions with background embebed.

**Comment by vdeparday** [comment]
@danielcasius I think there is a misunderstanding. It is great to have the option with and without background. The only issue is that we have this option only for two logos OpenDRI Standard and Color Negative. We would need to have the option to download with background for the logo OpenDRI white as well as for the other logos: CfR, UR, etc...
Does that make sense?

**Comment by shanikadhettige** [comment]
@danielcasius @andresgnlez

**Comment by danicaso-vizzuality** [comment]
Hi all. InnovationLab brand guidelines doesn't include an official version of the logos with a box surrounding them (like Facebook does), not talking about assets but about brand guidelines. Most of the brands are like us, and version with background embedded is not part of brand assets. Here I share some examples:
Twitter. https://about.twitter.com/company/brand-assets
YouTube. https://www.youtube.com/yt/brand/downloads.html
LinkedIn. https://brand.linkedin.com/downloads
Kickstarter. https://www.kickstarter.com/help/brand_assets
Instagram. https://www.instagram-brand.com

That's why we suggested remove those versions with background in OpenDRI as a solution to this issue.
