### ISSUE TITLE
Project page and related news

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#99]
We should put the related news on the right side, rather than on the bottom. Then the page will look a bit less blend and it will also move the information up for the user.

**Comment by sergioestella** [comment]
Sounds good. Do you think we should leave bellow the module including "related projects" as it was in the design? I think it does make sense if we will add "related news" in the sidebar.

**Comment by shanikadhettige** [comment]
@vdeparday @sergioestella @apercas Maybe you guys should revisit now that everything is properly linked. In the projects that have news I do think that it's quite nice but maybe we could also add related resources to the country project pages to add more to the pages. I think the news pages look good having stuff below as well as on the side.

**Comment by shanikadhettige** [comment]
It would be good if all the news at the bottom of a news page could link to other related news (like with the news shown on the projects) as opposed to the most recent one. Otherwise when you are visiting many different news pages it only shows the same three news posts on the bottom and it is actually pretty inconvenient and boring. 
I have already linked relevant news to news posts about the same country. I can also cross link topic wise. 

All news is organized with the following categories mentioned in the tags when relevant:
- Policy
- Software
- Field Update
- Open Data Movement
- Events
- Looking Back
- In the Press

**Comment by apercas** [comment]
Hello again, I've added related news and resources to the Project Box project, http://opendri.simbiotica.es/project/project-box-example/

Here's the result:
![image](https://cloud.githubusercontent.com/assets/704210/14707426/166e8f1e-07c5-11e6-8db0-1ede1c0556c8.png)

Now we have Recent News below, @shanikadhettige mentioned she wanted to use this space to link another related news but that would be redundant (having them on both the sidebar and the footer of the project), what else could we add here if we're removing the recent news?

Thank you!

**Comment by vdeparday** [comment]
This looks good to me. Actually, from our discussion last time, we will no longer have related resources, only related news. I guess we can keep it if we need it in the future but we should make sure that "related resources" doesn't appear if there are not related resources. 

Yes, you are right, we do not need recent News at the bottom of the page now. I think it is fine if we just have the footer. 

cc @rsoden

**Comment by apercas** [comment]
Yes, the related resources for a project won't show up if the custom field is empty, I'd leave the option there just in case, as you said, you'll want to add them.

About the recent news, should we remove them just for resources? ( + @sergioestella ) Let me know, thanks!

**Comment by sergioestella** [comment]
Let's discuss this in our meeting this "morning".

**Comment by apercas** [comment]
I think we can close this, can we?

**Comment by vdeparday** [comment]
Yes, I think that is fine.

**Comment by shanikadhettige** [comment]
@vdeparday @apercas 
But now related resources are not showing even when the custom field and link for a resource is added e.g. [Nepal](http://dev-gfdrr-opendri.pantheonsite.io/project/nepal/)
![screen shot 2016-05-04 at 4 39 03 pm](https://cloud.githubusercontent.com/assets/17725960/15028431/f1c26ed6-1216-11e6-9392-de5f5291a152.png)
![screen shot 2016-05-04 at 4 39 16 pm](https://cloud.githubusercontent.com/assets/17725960/15028432/f1c2bbe8-1216-11e6-9c3e-df12d86f1f15.png)

**Comment by tiagojsag** [comment]
hi, @shanikadhettige 

this regression is due to https://github.com/Vizzuality/openDRI/issues/117 that @apercas created and fixed a few weeks ago. I am assuming that it resulted from a request someone made, in which case we should review this sidebar and come to a final specification for its behavior. 

Let me know how we should proceed.
thanks
